keymap:
  # --- Single Key Remappings (Home Row) ---
  "0": [0]      # A -> A
  "1": [17]     # S -> T
  "2": [45]     # D -> N
  "3": [14]     # F -> E
  "5": [4]      # G -> H
  "4": [2]      # H -> D
  "38": [15]    # J -> R
  "40": [34]    # K -> I
  "37": [1]     # L -> S
  "41": [31]    # Semicolon -> O

  # --- Programmer Symbols (Top Row) ---
  # Left Hand
  "12": [50]     # Q -> < (Shift + Comma)
  "13": [61, 26] # W -> { (Shift + Left Bracket)
  "14": [61, 28] # E -> [
  "15": [56, 28] # R -> ( (Shift + 9)
  "9":  [56, 26] # V -> /
  # Right Hand
  "45": [61, 27] # V -> \
  "32": [56, 25] # U -> ) (Shift + 9)
  "34": [61, 25] # I -> ] (RAlt + 9)
  "31": [61, 29] # O -> }
  "35": [56, 50] # P -> > (Shift + 0)

  # --- Chord Mappings ---
  # Left Hand
  "0,1": [13]    # A+S -> W
  "1,2": [32]    # S+D -> U
  "2,3": [8]     # D+F -> C
  "0,5": [35]    # A+G -> P
  "0,2": [3]     # A+D -> F
  "1,3": [5]     # S+F -> G
  "0,3": [6]     # A+F -> Y
  "1,5": [12]    # S+G -> Q
  "2,5": [15]    # D+G -> R
  "3,5": [34]    # F+G -> I
  # Right Hand
  "38,40": [46]  # J+K -> M
  "37,40": [37]  # L+K -> L
  "4,41": [11]   # H+; -> B
  "37,41": [40]  # L+; -> K
  "4,40": [9]    # H+K -> V
  "37,38": [38]  # L+J -> J
  "4,37": [7]    # H+L -> X
  "40,41": [16]  # K+; -> Z
  "38,41": [45]  # J+; -> N
  "4,38": [17]   # H+J -> T

  # --- Triplets & Quadruplets ---
  #
  # Left Hand Codes: 0, 1, 2, 3, 5
  #
  # Left Hand
  "1,2,3": [34,45]                # S+D+F -> IN
  "0,1,2": [14,15]                # A+S+D -> ER
  "0,1,3": [17,14]                # S+D+G -> TE
  "0,2,3": [0,17]                 # A+S+D -> AT
  "0,2,5": [8,4]                # A+S+G -> NT
  "0,3,5": [14,45]                # A+S+G -> EN
  "0,1,5": [0,15]                 # A+S+G -> AR
  "1,2,5": [0,37]                 # A+S+G -> AL
  "2,3,5": [14,1]                 # A+S+G -> ES
  "1,3,5": [14,2]                 # A+S+G -> ED

  # Right Hand Codes: 4, 38, 40, 37, 41
  #
  # Right Hand
  "38,40,37": [15,14]           # L+J+K -> RE
  "40,37,41": [1,14]            # ;+L+K -> SE
  "38,37,41": [17,4]           # H+K+L -> ON
  "38,40,41": [31,15]           # H+K+L -> OR
  "4,40,41":  [1,17]            # J+L+; -> ST
  "4,40,37":  [2,14]            # L+J+K -> DE
  "4,37,41":  [37,14]           # ;+L+K -> LE
  "4,38,40":  [13,4]            # H+K+L -> CO
  "4,38,41":  [17,34]           # H+K+L -> TI
  "4,38,37":  [1,4]            # J+L+; -> NS

  # Left Hand Quadruplets
  "0,1,2,5": [5,4]             # A+S+D+G -> GHT
  "1,2,3,5": [8,40]            # S+D+F+G -> CK
  "0,1,2,3": [34,45,5]         # ING

  # Right Hand Quadruplets
  "4,37,40,41": [34,31,45]     # H+K+L+; -> ION
  "4,37,38,40": [8,17]         # H+K+L+; -> CT
