keymap:
  # --- Single Key Remappings (Home Row) ---
  "0": [0]      # A
  "1": [17]     # T
  "2": [45]     # N
  "3": [14]     # E
  "5": [4]      # H
  "4": [2]      # D
  "38": [15]    # R
  "40": [34]    # I
  "37": [1]     # S
  "41": [31]    # O

  # --- Programmer Symbols (Top Row) ---
  # Left Hand
  "12": [50]     # < (Shift + Comma)
  "13": [61, 26] # { (Shift + Left Bracket)
  "14": [61, 28] # [
  "15": [56, 28] # ( (Shift + 9)
  "9":  [56, 26] # /
  # Right Hand
  "45": [61, 27] # \
  "32": [56, 25] # ) (Shift + 9)
  "34": [61, 25] # ] (RAlt + 9)
  "31": [61, 29] # }
  "35": [56, 50] # > (Shift + 0)

  # --- Chord Mappings ---
  # Left Hand
  "0,1": [13]    # W
  "1,2": [32]    # U
  "2,3": [8]     # C
  "0,5": [35]    # P
  "0,2": [3]     # F
  "1,3": [5]     # G
  "0,3": [6]     # Y
  "1,5": [12]    # Q
  "2,5": [15]    # R
  "3,5": [34]    # I
  # Right Hand
  "38,40": [46]  # M
  "37,40": [37]  # L
  "4,41": [11]   # B
  "37,41": [40]  # K
  "4,40": [9]    # V
  "37,38": [38]  # J
  "4,37": [7]    # X
  "40,41": [16]  # Z
  "38,41": [45]  # N
  "4,38": [17]   # T

  # --- Triplets & Quadruplets ---
  #
  # Left Hand Codes: 0, 1, 2, 3, 5
  #
  # Left Hand
  "1,2,3": [34,45]                # IN
  "0,1,2": [14,15]                # ER
  "0,1,3": [17,14]                # TE
  "0,2,3": [0,17]                 # AT
  "0,2,5": [8,4]                  # NT
  "0,3,5": [14,45]                # EN
  "0,1,5": [0,15]                 # AR
  "1,2,5": [0,37]                 # AL
  "2,3,5": [14,1]                 # ES
  "1,3,5": [14,2]                 # ED

  # Right Hand Codes: 4, 38, 40, 37, 41
  #
  # Right Hand
  "38,40,37": [15,14]           # RE
  "40,37,41": [1,14]            # SE
  "38,37,41": [17,4]            # ON
  "38,40,41": [31,15]           # OR
  "4,40,41":  [1,17]            # ST
  # "4,40,37":  [2,14]          # DE -> NEW
  # "4,37,41":  [37,14]         # LE -> NEW
  "4,38,40":  [13,4]            # CO
  "4,38,41":  [17,34]           # TI
  "4,38,37":  [1,4]             # NS

  # Left Hand Quadruplets
  "0,1,2,5": [5,4]             # GHT
  "1,2,3,5": [8,40]            # CK
  "0,1,2,3": [34,45,5]         # ING
  "0,1,3,5": [34,14,1]         # IES

  # Right Hand Quadruplets
  "4,37,40,41": [34,31,45]     # ION
  "4,37,38,40": [8,17]         # CT
  "37,38,40,41": [14,45,17]    # ENT
  "4,38,37,41": [0,11,37,14]   # ABLE
