keymap:
  # --- Single Key Remappings (Home Row) ---
  "0": [0]      # A -> A
  "1": [17]     # S -> T
  "2": [45]     # D -> N
  "3": [14]     # F -> E
  "5": [4]      # G -> H
  "4": [2]      # H -> D
  "38": [15]    # J -> R
  "40": [34]    # K -> I
  "37": [1]     # L -> S
  "41": [31]    # Semicolon -> O

  # --- Programmer Symbols (Top Row) ---
  # Left Hand
  "12": [50]     # Q -> < (Shift + Comma)
  "13": [61, 26] # W -> { (Shift + Left Bracket)
  "14": [61, 28] # E -> [
  "15": [56, 28] # R -> ( (Shift + 9)
  "9":  [56, 26] # V -> /
  # Right Hand
  "45": [61, 27] # V -> \
  "32": [56, 25] # U -> ) (Shift + 9)
  "34": [61, 25] # I -> ] (RAlt + 9)
  "31": [61, 29] # O -> }
  "35": [56, 50] # P -> > (Shift + 0)

  # --- Chord Mappings ---
  # Left Hand
  "0,1": [13]    # A+S -> W
  "1,2": [32]    # S+D -> U
  "2,3": [8]     # D+F -> C
  "0,5": [35]    # A+G -> P
  "0,2": [3]     # A+D -> F
  "1,3": [5]     # S+F -> G
  "0,3": [6]     # A+F -> Y
  "1,5": [12]    # S+G -> Q
  # Right Hand
  "38,40": [46]  # J+K -> M
  "37,40": [37]  # L+K -> L
  "4,41": [11]   # H+; -> B
  "37,41": [40]  # L+; -> K
  "4,40": [9]    # H+K -> V
  "37,38": [38]  # L+J -> J
  "4,37": [7]    # H+L -> X
  "40,41": [16]  # K+; -> Z
